from enum import Enum

class CommandHitValues(Enum):
    HELP = 1
    TEST = 2
    EDIT = 3
    SEARCH = 4
    SETTINGS = 5
    LIST_SETTINGS = 6

    ADD_PLAYLIST = 7
    ADD_PLAYLIST_FROM_YOUTUBE = 8
    DELETE_PLAYLIST = 9
    RESTORE_PLAYLIST = 10
    LIST_WATCHED_PLAYLISTS = 11
    DETAILS_PLAYLIST = 12
    FETCH_PLAYLIST = 13
    PRUNE_PLAYLIST = 14
    PURGE_PLAYLIST = 15
    PURGE = 16
    RESET_PLAYLIST = 17
    EXPORT_PLAYLIST = 18
    UNWATCH_ALL_PLAYLIST = 19

    PLAY = 20

    ADD_STREAM = 21
    ADD_MULTIPLE_STREAMS = 22
    DELETE_STREAM = 23
    RESTORE_STREAM = 24

    ADD_SOURCE = 25
    DELETE_SOURCES = 26
    RESTORE_SOURCE = 27
    LIST_SOURCES = 28
    OPEN_SOURCE = 29

    LIST_SOFT_DELETED = 30
    REFACTOR_OLD = 31
    