from enum import Enum

class CommandHitValues(Enum):
    HELP = 1
    TEST = 2
    EDIT = 3
    SEARCH = 4
    SETTINGS = 5
    LIST_SETTINGS = 6

    ADD_PLAYLIST = 7
    ADD_PLAYLIST_FROM_YOUTUBE = 8
    DELETE_PLAYLIST = 9
    RESTORE_PLAYLIST = 10
    LIST_PLAYLISTS = 11
    DETAILS_PLAYLIST = 12
    FETCH_PLAYLIST = 13
    PRUNE_PLAYLIST = 14
    PURGE_PLAYLIST = 15
    PURGE = 16
    RESET_PLAYLIST = 17
    DOWNLOAD_PLAYLIST = 18
    EXPORT_PLAYLIST = 19
    UNWATCH_ALL_PLAYLIST = 20
    
    PLAY = 21
    
    ADD_STREAM = 22
    ADD_MULTIPLE_STREAMS = 23
    DELETE_STREAM = 24
    RESTORE_STREAM = 25
    
    ADD_SOURCE = 26
    DELETE_SOURCES = 27
    RESTORE_SOURCE = 28
    LIST_SOURCES = 29
    OPEN_SOURCE = 30
    
    LIST_SOFT_DELETED = 31
    REFACTOR_OLD = 32
    